# Generated by Django 4.2.7 on 2023-11-18 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blinddate', '0002_alter_profile_about_me'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_foto',
            field=models.ImageField(blank=True, null=True, upload_to='profileImages/'),
        ),
    ]
