# Generated by Django 4.2.7 on 2023-11-18 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blinddate', '0003_alter_profile_user_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_foto',
            field=models.ImageField(blank=True, null=True, upload_to='blinddate/media/profileImages/'),
        ),
    ]
