# Generated by Django 4.2.7 on 2023-11-24 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blinddate', '0006_chat_match_profile_hobbys_profile_interests'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_list_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matchlist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='match',
            name='matches',
            field=models.ManyToManyField(to='blinddate.profile'),
        ),
    ]
