# Generated by Django 4.2.7 on 2023-11-26 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blinddate', '0008_match_not_match_but_seen_alter_match_matches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='not_match_but_seen',
            field=models.ManyToManyField(blank=True, related_name='not_match_but_seen', to='blinddate.profile'),
        ),
    ]
