# Generated by Django 4.2.7 on 2023-11-27 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blinddate', '0009_alter_match_not_match_but_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_foto',
            field=models.ImageField(blank=True, null=True, upload_to='profileImages/'),
        ),
    ]
