# Generated by Django 4.2.7 on 2023-11-28 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blinddate', '0012_alter_chat_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
