# Generated by Django 4.2.7 on 2023-11-28 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blinddate', '0014_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='text',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='timestamp',
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=400)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_message', to='blinddate.chat')),
            ],
        ),
    ]
